### PR TITLE
Several fixes for 5.6 toolchain

### PR DESCRIPTION
**Pull request by kateinoigakukun**
- Reactor model support
- Update sanitizer support object

This is required to resolve https://github.com/TokamakUI/Tokamak/pull/475

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Thank you so much for investigating it. This is great, I really appreciate your hard work on these issues! 🙏

**Comment by MaxDesiatov** [comment]
Do we still need `so_sanitizer.wasm` file for this to work? With this PR as is I get `~/.carton/static/so_sanitizer.wasm: No such file or directory` error, but I'm not sure if this file is no longer needed and we're no longer supposed to link with it, or the file was just lost in my `static.zip` archival process.

**Comment by kateinoigakukun** [comment]
Hmm, weird. I didn't change anything except for the content of so_sanitizer.wasm. The support object file is still necessary.

**Comment by MaxDesiatov** [comment]
I had to point tests utilizing Tokamak to the branch of https://github.com/TokamakUI/Tokamak/pull/475. Waiting for that to be approved, then will tag new Tokamak and merge this one.

**Review by MaxDesiatov — APPROVED** [review]

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
