### PR TITLE
Use ghcr.io/swiftwasm/swift as base image

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Update Dockerfile to use ghcr.io/swiftwasm/swift as base image and update default toolchain version as 5.3 release

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Looks great! Let's switch to the 5.3.0 toolchain here and in the `swiftwasm-docker` repo as soon as it's tagged and assets are available.

**Review by MaxDesiatov — APPROVED** [review]
👍

**Review by MaxDesiatov — CHANGES_REQUESTED** [review]
Please also update `DefaultToolchain.swift`

**Comment by kateinoigakukun** [comment]
> Please also update DefaultToolchain.swift

It's already updated

**Review by MaxDesiatov — APPROVED** [review]
Ah, sorry I missed that 🤦‍♂️

**Pull request merged**
