### PR TITLE
Add `test` command test with no arguments

### PR DESCRIPTION
**Pull request by thecb4**
This is in support of #99 

Added
* Test Command Test with no arguments

Changed
* Moved TestApp, entrypoint, package.json, and package-lock.json folder to Test/Fixtures/carton-test
* Script for GitHub Actions now builds (including tests) then runs the tests separately. 
* Dockerfile now builds (including tests) then runs the tests separately. 

Removed
* Script for GitHub Actions no longer references TestApp
* Dockerfile no longer references TestApp

### CODE REVIEW

**Review by MaxDesiatov — CHANGES_REQUESTED** [review]
Could you move the `entrypoint` directory and `package.json`/`package-lock.json` back to the root from the `Fixtures` dir? It's used for entrypoints for all commands, not just in the fixture.

**Comment by thecb4** [comment]
Sure - moved them back.

**Comment by MaxDesiatov** [comment]
And the `entrypoint` directory too please 🙂

**Review by MaxDesiatov — APPROVED** [review]
LGTM, thank you 👏

**Pull request merged**
