### PR TITLE
Bump JavaScriptKit dependency to 0.13.0

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Review by kateinoigakukun — APPROVED** [review]

**Review by yonihemi — APPROVED** [review]

**Comment by pedrovgs** [comment]
@MaxDesiatov this is the release that contains the fix for ``--debug-info`` param, isn't it?

**Comment by MaxDesiatov** [comment]
Yes, all the latest code from the `main` branch of the JSKit repo.

**Comment by pedrovgs** [comment]
Shouldn't we tag this release so the docker image and the binaries are available for users as version 0.13.0? I don't know if you do this as part of this PR or you wait until is merged. Asking just in case @MaxDesiatov 😃  Thanks for the release btw.

**Comment by MaxDesiatov** [comment]
Sure, the release will be tagged after https://github.com/swiftwasm/carton/pull/305 is merged. #306 is just a dependency update PR.

**Comment by pedrovgs** [comment]
Great thanks for the update! I see it is already approved so I guess it is a matter of time 😃

**Comment by MaxDesiatov** [comment]
Merged and tagged now. 0.13.0 Docker image should be ready as well. Due to some incompatibilities with Tokamak I'm seeing, I think I'll wait for SwiftWasm 5.6 release to fix this before distributing latest `carton` on Homebrew and widely announcing it. But I hope it works well for you in the meantime.

**Comment by pedrovgs** [comment]
Thanks @MaxDesiatov 😃

**Pull request merged**
