### PR TITLE
Implement `--custom-index-page` option

### LINKED ISSUE #100: Allow carton to use a provided HTML template file
I think it would be a great addition to have the ability to specify an HTML template for carton to use in the event that someone wants to customize it. The feature would be similar to `HtmlWebpackPlugin` and allow for specifying a path to an HTML template file, that carton could then inject the proper script tags into.

What are your thoughts on this? Has there already been something similar thought of or requested? I would be happy to contribute a PR to help bring this functionality!

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Allows passing a path to your custom `index.html` as `--custom-index-page` to `carton dev` and `carton bundle`. The entrypoint script is then injected into this file with a simple text substitution looking for a closing `</head>` tag. The assumption is that your custom `<body>` is not supposed to contain an unescaped `<head></head>`, and adding a dependency on a proper HTML parser to implement this injection is too costly.

Depends on #97.

Resolves #100.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Thanks, could you also review #97 first so that these two land as separate commits to `main`?

**Comment by ie-ahm-robox** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **Sources/carton/Commands/Bundle.swift#L43** - Function body should span 50 lines or less excluding comments and whitespace: currently spans 52 lines (`function_body_length`)
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against fa99714a09520e882ee55c30bdd44dc0f167fe35
</p>

**Comment by ie-ahm-robox** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **Sources/carton/Commands/Bundle.swift#L43** - Function body should span 50 lines or less excluding comments and whitespace: currently spans 52 lines (`function_body_length`)
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against fa99714a09520e882ee55c30bdd44dc0f167fe35
</p>

**Comment by ie-ahm-robox** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **Sources/carton/Helpers/FileSystem.swift#L49** - FIXMEs should be resolved (should use `UnitInformationSto...). (`todo`)
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 17e82598fdf225053e1bb9a81a1ab9bbf03bbd74
</p>

**Pull request merged**
